import { CountryOption } from "../models/interfaces";

export const NBA_COUNTRIES: CountryOption[] = [
  { name: 'USA' },
  { name: 'Canada' },
  { name: 'France' },
  { name: 'Australia' },
  { name: 'Serbia' },
  { name: 'Lithuania' },
  { name: 'Germany' },
  { name: 'Cameroon' },
  { name: 'Bosnia and Herzegovina' },
  { name: 'Latvia' },
  { name: 'Brazil' },
  { name: 'Nigeria' },
  { name: 'Finland' },
  { name: 'Georgia' },
  { name: 'Switzerland' },
  { name: 'Greece' },
  { name: 'Slovenia' },
  { name: 'Montenegro' },
  { name: 'Spain' },
  { name: 'Czech Republic' },
  { name: 'Dominican Republic' },
  { name: 'Turkey' },
  { name: 'Sweden' },
  { name: 'Mexico' },
  { name: 'Colombia' },
  { name: 'Puerto Rico' }
];
